# Generated by Django 2.2.3 on 2019-07-23 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0009_auto_20190722_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
