# Generated by Django 2.2.3 on 2019-07-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_tweet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
    ]
