# Generated by Django 2.2.3 on 2019-07-29 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0013_auto_20190729_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='owner',
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_by', to='tweets.Tweet'),
        ),
    ]
